SELECT
IFNULL(CONCAT(GROUP_CONCAT(sag1.767_3_k),'-',GROUP_CONCAT(sag1.767_2_k)),'0-0') AS '767_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.768_3_k),'-',GROUP_CONCAT(sag1.768_2_k)),'0-0') AS '768_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.769_3_k),'-',GROUP_CONCAT(sag1.769_2_k)),'0-0') AS '769_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.770_3_k),'-',GROUP_CONCAT(sag1.770_2_k)),'0-0') AS '770_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.771_3_k),'-',GROUP_CONCAT(sag1.771_2_k)),'0-0') AS '771_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.772_3_k),'-',GROUP_CONCAT(sag1.772_2_k)),'0-0') AS '772_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.773_3_k),'-',GROUP_CONCAT(sag1.773_2_k)),'0-0') AS '773_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.774_3_k),'-',GROUP_CONCAT(sag1.774_2_k)),'0-0') AS '774_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.775_3_k),'-',GROUP_CONCAT(sag1.775_2_k)),'0-0') AS '775_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.776_3_k),'-',GROUP_CONCAT(sag1.776_2_k)),'0-0') AS '776_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.777_3_k),'-',GROUP_CONCAT(sag1.777_2_k)),'0-0') AS '777_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.778_3_k),'-',GROUP_CONCAT(sag1.778_2_k)),'0-0') AS '778_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.779_3_k),'-',GROUP_CONCAT(sag1.779_2_k)),'0-0') AS '779_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.780_3_k),'-',GROUP_CONCAT(sag1.780_2_k)),'0-0') AS '780_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.781_3_k),'-',GROUP_CONCAT(sag1.781_2_k)),'0-0') AS '781_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.782_3_k),'-',GROUP_CONCAT(sag1.782_2_k)),'0-0') AS '782_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.783_3_k),'-',GROUP_CONCAT(sag1.783_2_k)),'0-0') AS '783_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.784_3_k),'-',GROUP_CONCAT(sag1.784_2_k)),'0-0') AS '784_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.785_3_k),'-',GROUP_CONCAT(sag1.785_2_k)),'0-0') AS '785_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.786_3_k),'-',GROUP_CONCAT(sag1.786_2_k)),'0-0') AS '786_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.787_3_k),'-',GROUP_CONCAT(sag1.787_2_k)),'0-0') AS '787_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.789_3_k),'-',GROUP_CONCAT(sag1.789_2_k)),'0-0') AS '789_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.1534_3_k),'-',GROUP_CONCAT(sag1.1534_2_k)),'0-0') AS '1534_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.790_3_k),'-',GROUP_CONCAT(sag1.790_2_k)),'0-0') AS '790_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.791_3_k),'-',GROUP_CONCAT(sag1.791_2_k)),'0-0') AS '791_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.1536_3_k),'-',GROUP_CONCAT(sag1.1536_2_k)),'0-0') AS '1536_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.792_3_k),'-',GROUP_CONCAT(sag1.792_2_k)),'0-0') AS '792_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.793_3_k),'-',GROUP_CONCAT(sag1.793_2_k)),'0-0') AS '793_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.794_3_k),'-',GROUP_CONCAT(sag1.794_2_k)),'0-0') AS '794_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.795_3_k),'-',GROUP_CONCAT(sag1.795_2_k)),'0-0') AS '795_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.796_3_k),'-',GROUP_CONCAT(sag1.796_2_k)),'0-0') AS '796_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.797_3_k),'-',GROUP_CONCAT(sag1.797_2_k)),'0-0') AS '797_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.798_3_k),'-',GROUP_CONCAT(sag1.798_2_k)),'0-0') AS '798_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.800_3_k),'-',GROUP_CONCAT(sag1.800_2_k)),'0-0') AS '800_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.801_3_k),'-',GROUP_CONCAT(sag1.801_2_k)),'0-0') AS '801_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.802_3_k),'-',GROUP_CONCAT(sag1.802_2_k)),'0-0') AS '802_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.803_3_k),'-',GROUP_CONCAT(sag1.803_2_k)),'0-0') AS '803_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.804_3_k),'-',GROUP_CONCAT(sag1.804_2_k)),'0-0') AS '804_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.805_3_k),'-',GROUP_CONCAT(sag1.805_2_k)),'0-0') AS '805_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.806_3_k),'-',GROUP_CONCAT(sag1.806_2_k)),'0-0') AS '806_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.807_3_k),'-',GROUP_CONCAT(sag1.807_2_k)),'0-0') AS '807_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.808_3_k),'-',GROUP_CONCAT(sag1.808_2_k)),'0-0') AS '808_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.809_3_k),'-',GROUP_CONCAT(sag1.809_2_k)),'0-0') AS '809_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.810_3_k),'-',GROUP_CONCAT(sag1.810_2_k)),'0-0') AS '810_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.811_3_k),'-',GROUP_CONCAT(sag1.811_2_k)),'0-0') AS '811_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.812_3_k),'-',GROUP_CONCAT(sag1.812_2_k)),'0-0') AS '812_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.813_3_k),'-',GROUP_CONCAT(sag1.813_2_k)),'0-0') AS '813_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.1538_3_k),'-',GROUP_CONCAT(sag1.1538_2_k)),'0-0') AS '1538_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.814_3_k),'-',GROUP_CONCAT(sag1.814_2_k)),'0-0') AS '814_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.815_3_k),'-',GROUP_CONCAT(sag1.815_2_k)),'0-0') AS '815_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.816_3_k),'-',GROUP_CONCAT(sag1.816_2_k)),'0-0') AS '816_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.817_3_k),'-',GROUP_CONCAT(sag1.817_2_k)),'0-0') AS '817_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.818_3_k),'-',GROUP_CONCAT(sag1.818_2_k)),'0-0') AS '818_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.819_3_k),'-',GROUP_CONCAT(sag1.819_2_k)),'0-0') AS '819_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.820_3_k),'-',GROUP_CONCAT(sag1.820_2_k)),'0-0') AS '820_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.821_3_k),'-',GROUP_CONCAT(sag1.821_2_k)),'0-0') AS '821_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.822_3_k),'-',GROUP_CONCAT(sag1.822_2_k)),'0-0') AS '822_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.823_3_k),'-',GROUP_CONCAT(sag1.823_2_k)),'0-0') AS '823_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.828_3_k),'-',GROUP_CONCAT(sag1.828_2_k)),'0-0') AS '828_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.829_3_k),'-',GROUP_CONCAT(sag1.829_2_k)),'0-0') AS '829_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.831_3_k),'-',GROUP_CONCAT(sag1.831_2_k)),'0-0') AS '831_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.830_3_k),'-',GROUP_CONCAT(sag1.830_2_k)),'0-0') AS '830_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.833_3_k),'-',GROUP_CONCAT(sag1.833_2_k)),'0-0') AS '833_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.832_3_k),'-',GROUP_CONCAT(sag1.832_2_k)),'0-0') AS '832_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.827_3_k),'-',GROUP_CONCAT(sag1.827_2_k)),'0-0') AS '827_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.1545_3_k),'-',GROUP_CONCAT(sag1.1545_2_k)),'0-0') AS '1545_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.826_3_k),'-',GROUP_CONCAT(sag1.826_2_k)),'0-0') AS '826_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.1543_3_k),'-',GROUP_CONCAT(sag1.1543_2_k)),'0-0') AS '1543_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.825_3_k),'-',GROUP_CONCAT(sag1.825_2_k)),'0-0') AS '825_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.834_3_k),'-',GROUP_CONCAT(sag1.834_2_k)),'0-0') AS '834_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.835_3_k),'-',GROUP_CONCAT(sag1.835_2_k)),'0-0') AS '835_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.836_3_k),'-',GROUP_CONCAT(sag1.836_2_k)),'0-0') AS '836_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.837_3_k),'-',GROUP_CONCAT(sag1.837_2_k)),'0-0') AS '837_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.838_3_k),'-',GROUP_CONCAT(sag1.838_2_k)),'0-0') AS '838_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.1540_3_k),'-',GROUP_CONCAT(sag1.1540_2_k)),'0-0') AS '1540_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.840_3_k),'-',GROUP_CONCAT(sag1.840_2_k)),'0-0') AS '840_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.841_3_k),'-',GROUP_CONCAT(sag1.841_2_k)),'0-0') AS '841_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.842_3_k),'-',GROUP_CONCAT(sag1.842_2_k)),'0-0') AS '842_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.843_3_k),'-',GROUP_CONCAT(sag1.843_2_k)),'0-0') AS '843_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.1542_3_k),'-',GROUP_CONCAT(sag1.1542_2_k)),'0-0') AS '1542_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.844_3_k),'-',GROUP_CONCAT(sag1.844_2_k)),'0-0') AS '844_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.846_3_k),'-',GROUP_CONCAT(sag1.846_2_k)),'0-0') AS '846_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.848_3_k),'-',GROUP_CONCAT(sag1.848_2_k)),'0-0') AS '848_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.847_3_k),'-',GROUP_CONCAT(sag1.847_2_k)),'0-0') AS '847_3_2_k',
IFNULL(CONCAT(GROUP_CONCAT(sag1.767_3_m),'-',GROUP_CONCAT(sag1.767_2_m)),'0-0') AS '767_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.768_3_m),'-',GROUP_CONCAT(sag1.768_2_m)),'0-0') AS '768_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.769_3_m),'-',GROUP_CONCAT(sag1.769_2_m)),'0-0') AS '769_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.770_3_m),'-',GROUP_CONCAT(sag1.770_2_m)),'0-0') AS '770_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.771_3_m),'-',GROUP_CONCAT(sag1.771_2_m)),'0-0') AS '771_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.772_3_m),'-',GROUP_CONCAT(sag1.772_2_m)),'0-0') AS '772_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.773_3_m),'-',GROUP_CONCAT(sag1.773_2_m)),'0-0') AS '773_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.774_3_m),'-',GROUP_CONCAT(sag1.774_2_m)),'0-0') AS '774_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.775_3_m),'-',GROUP_CONCAT(sag1.775_2_m)),'0-0') AS '775_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.776_3_m),'-',GROUP_CONCAT(sag1.776_2_m)),'0-0') AS '776_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.777_3_m),'-',GROUP_CONCAT(sag1.777_2_m)),'0-0') AS '777_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.778_3_m),'-',GROUP_CONCAT(sag1.778_2_m)),'0-0') AS '778_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.779_3_m),'-',GROUP_CONCAT(sag1.779_2_m)),'0-0') AS '779_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.780_3_m),'-',GROUP_CONCAT(sag1.780_2_m)),'0-0') AS '780_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.781_3_m),'-',GROUP_CONCAT(sag1.781_2_m)),'0-0') AS '781_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.782_3_m),'-',GROUP_CONCAT(sag1.782_2_m)),'0-0') AS '782_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.783_3_m),'-',GROUP_CONCAT(sag1.783_2_m)),'0-0') AS '783_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.784_3_m),'-',GROUP_CONCAT(sag1.784_2_m)),'0-0') AS '784_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.785_3_m),'-',GROUP_CONCAT(sag1.785_2_m)),'0-0') AS '785_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.786_3_m),'-',GROUP_CONCAT(sag1.786_2_m)),'0-0') AS '786_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.787_3_m),'-',GROUP_CONCAT(sag1.787_2_m)),'0-0') AS '787_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.789_3_m),'-',GROUP_CONCAT(sag1.789_2_m)),'0-0') AS '789_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.1534_3_m),'-',GROUP_CONCAT(sag1.1534_2_m)),'0-0') AS '1534_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.790_3_m),'-',GROUP_CONCAT(sag1.790_2_m)),'0-0') AS '790_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.791_3_m),'-',GROUP_CONCAT(sag1.791_2_m)),'0-0') AS '791_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.1536_3_m),'-',GROUP_CONCAT(sag1.1536_2_m)),'0-0') AS '1536_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.792_3_m),'-',GROUP_CONCAT(sag1.792_2_m)),'0-0') AS '792_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.793_3_m),'-',GROUP_CONCAT(sag1.793_2_m)),'0-0') AS '793_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.794_3_m),'-',GROUP_CONCAT(sag1.794_2_m)),'0-0') AS '794_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.795_3_m),'-',GROUP_CONCAT(sag1.795_2_m)),'0-0') AS '795_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.796_3_m),'-',GROUP_CONCAT(sag1.796_2_m)),'0-0') AS '796_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.797_3_m),'-',GROUP_CONCAT(sag1.797_2_m)),'0-0') AS '797_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.798_3_m),'-',GROUP_CONCAT(sag1.798_2_m)),'0-0') AS '798_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.800_3_m),'-',GROUP_CONCAT(sag1.800_2_m)),'0-0') AS '800_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.801_3_m),'-',GROUP_CONCAT(sag1.801_2_m)),'0-0') AS '801_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.802_3_m),'-',GROUP_CONCAT(sag1.802_2_m)),'0-0') AS '802_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.803_3_m),'-',GROUP_CONCAT(sag1.803_2_m)),'0-0') AS '803_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.804_3_m),'-',GROUP_CONCAT(sag1.804_2_m)),'0-0') AS '804_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.805_3_m),'-',GROUP_CONCAT(sag1.805_2_m)),'0-0') AS '805_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.806_3_m),'-',GROUP_CONCAT(sag1.806_2_m)),'0-0') AS '806_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.807_3_m),'-',GROUP_CONCAT(sag1.807_2_m)),'0-0') AS '807_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.808_3_m),'-',GROUP_CONCAT(sag1.808_2_m)),'0-0') AS '808_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.809_3_m),'-',GROUP_CONCAT(sag1.809_2_m)),'0-0') AS '809_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.810_3_m),'-',GROUP_CONCAT(sag1.810_2_m)),'0-0') AS '810_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.811_3_m),'-',GROUP_CONCAT(sag1.811_2_m)),'0-0') AS '811_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.812_3_m),'-',GROUP_CONCAT(sag1.812_2_m)),'0-0') AS '812_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.813_3_m),'-',GROUP_CONCAT(sag1.813_2_m)),'0-0') AS '813_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.1538_3_m),'-',GROUP_CONCAT(sag1.1538_2_m)),'0-0') AS '1538_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.814_3_m),'-',GROUP_CONCAT(sag1.814_2_m)),'0-0') AS '814_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.815_3_m),'-',GROUP_CONCAT(sag1.815_2_m)),'0-0') AS '815_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.816_3_m),'-',GROUP_CONCAT(sag1.816_2_m)),'0-0') AS '816_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.817_3_m),'-',GROUP_CONCAT(sag1.817_2_m)),'0-0') AS '817_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.818_3_m),'-',GROUP_CONCAT(sag1.818_2_m)),'0-0') AS '818_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.819_3_m),'-',GROUP_CONCAT(sag1.819_2_m)),'0-0') AS '819_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.820_3_m),'-',GROUP_CONCAT(sag1.820_2_m)),'0-0') AS '820_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.821_3_m),'-',GROUP_CONCAT(sag1.821_2_m)),'0-0') AS '821_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.822_3_m),'-',GROUP_CONCAT(sag1.822_2_m)),'0-0') AS '822_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.823_3_m),'-',GROUP_CONCAT(sag1.823_2_m)),'0-0') AS '823_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.828_3_m),'-',GROUP_CONCAT(sag1.828_2_m)),'0-0') AS '828_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.829_3_m),'-',GROUP_CONCAT(sag1.829_2_m)),'0-0') AS '829_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.831_3_m),'-',GROUP_CONCAT(sag1.831_2_m)),'0-0') AS '831_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.830_3_m),'-',GROUP_CONCAT(sag1.830_2_m)),'0-0') AS '830_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.833_3_m),'-',GROUP_CONCAT(sag1.833_2_m)),'0-0') AS '833_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.832_3_m),'-',GROUP_CONCAT(sag1.832_2_m)),'0-0') AS '832_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.827_3_m),'-',GROUP_CONCAT(sag1.827_2_m)),'0-0') AS '827_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.1545_3_m),'-',GROUP_CONCAT(sag1.1545_2_m)),'0-0') AS '1545_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.826_3_m),'-',GROUP_CONCAT(sag1.826_2_m)),'0-0') AS '826_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.1543_3_m),'-',GROUP_CONCAT(sag1.1543_2_m)),'0-0') AS '1543_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.825_3_m),'-',GROUP_CONCAT(sag1.825_2_m)),'0-0') AS '825_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.834_3_m),'-',GROUP_CONCAT(sag1.834_2_m)),'0-0') AS '834_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.835_3_m),'-',GROUP_CONCAT(sag1.835_2_m)),'0-0') AS '835_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.836_3_m),'-',GROUP_CONCAT(sag1.836_2_m)),'0-0') AS '836_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.837_3_m),'-',GROUP_CONCAT(sag1.837_2_m)),'0-0') AS '837_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.838_3_m),'-',GROUP_CONCAT(sag1.838_2_m)),'0-0') AS '838_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.1540_3_m),'-',GROUP_CONCAT(sag1.1540_2_m)),'0-0') AS '1540_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.840_3_m),'-',GROUP_CONCAT(sag1.840_2_m)),'0-0') AS '840_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.841_3_m),'-',GROUP_CONCAT(sag1.841_2_m)),'0-0') AS '841_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.842_3_m),'-',GROUP_CONCAT(sag1.842_2_m)),'0-0') AS '842_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.843_3_m),'-',GROUP_CONCAT(sag1.843_2_m)),'0-0') AS '843_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.1542_3_m),'-',GROUP_CONCAT(sag1.1542_2_m)),'0-0') AS '1542_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.844_3_m),'-',GROUP_CONCAT(sag1.844_2_m)),'0-0') AS '844_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.846_3_m),'-',GROUP_CONCAT(sag1.846_2_m)),'0-0') AS '846_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.848_3_m),'-',GROUP_CONCAT(sag1.848_2_m)),'0-0') AS '848_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.847_3_m),'-',GROUP_CONCAT(sag1.847_2_m)),'0-0') AS '847_3_2_m',
IFNULL(CONCAT(GROUP_CONCAT(sag1.767_3_n),'-',GROUP_CONCAT(sag1.767_2_n)),'0-0') AS '767_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.768_3_n),'-',GROUP_CONCAT(sag1.768_2_n)),'0-0') AS '768_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.769_3_n),'-',GROUP_CONCAT(sag1.769_2_n)),'0-0') AS '769_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.770_3_n),'-',GROUP_CONCAT(sag1.770_2_n)),'0-0') AS '770_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.771_3_n),'-',GROUP_CONCAT(sag1.771_2_n)),'0-0') AS '771_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.772_3_n),'-',GROUP_CONCAT(sag1.772_2_n)),'0-0') AS '772_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.773_3_n),'-',GROUP_CONCAT(sag1.773_2_n)),'0-0') AS '773_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.774_3_n),'-',GROUP_CONCAT(sag1.774_2_n)),'0-0') AS '774_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.775_3_n),'-',GROUP_CONCAT(sag1.775_2_n)),'0-0') AS '775_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.776_3_n),'-',GROUP_CONCAT(sag1.776_2_n)),'0-0') AS '776_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.777_3_n),'-',GROUP_CONCAT(sag1.777_2_n)),'0-0') AS '777_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.778_3_n),'-',GROUP_CONCAT(sag1.778_2_n)),'0-0') AS '778_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.779_3_n),'-',GROUP_CONCAT(sag1.779_2_n)),'0-0') AS '779_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.780_3_n),'-',GROUP_CONCAT(sag1.780_2_n)),'0-0') AS '780_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.781_3_n),'-',GROUP_CONCAT(sag1.781_2_n)),'0-0') AS '781_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.782_3_n),'-',GROUP_CONCAT(sag1.782_2_n)),'0-0') AS '782_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.783_3_n),'-',GROUP_CONCAT(sag1.783_2_n)),'0-0') AS '783_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.784_3_n),'-',GROUP_CONCAT(sag1.784_2_n)),'0-0') AS '784_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.785_3_n),'-',GROUP_CONCAT(sag1.785_2_n)),'0-0') AS '785_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.786_3_n),'-',GROUP_CONCAT(sag1.786_2_n)),'0-0') AS '786_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.787_3_n),'-',GROUP_CONCAT(sag1.787_2_n)),'0-0') AS '787_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.789_3_n),'-',GROUP_CONCAT(sag1.789_2_n)),'0-0') AS '789_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.1534_3_n),'-',GROUP_CONCAT(sag1.1534_2_n)),'0-0') AS '1534_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.790_3_n),'-',GROUP_CONCAT(sag1.790_2_n)),'0-0') AS '790_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.791_3_n),'-',GROUP_CONCAT(sag1.791_2_n)),'0-0') AS '791_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.1536_3_n),'-',GROUP_CONCAT(sag1.1536_2_n)),'0-0') AS '1536_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.792_3_n),'-',GROUP_CONCAT(sag1.792_2_n)),'0-0') AS '792_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.793_3_n),'-',GROUP_CONCAT(sag1.793_2_n)),'0-0') AS '793_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.794_3_n),'-',GROUP_CONCAT(sag1.794_2_n)),'0-0') AS '794_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.795_3_n),'-',GROUP_CONCAT(sag1.795_2_n)),'0-0') AS '795_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.796_3_n),'-',GROUP_CONCAT(sag1.796_2_n)),'0-0') AS '796_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.797_3_n),'-',GROUP_CONCAT(sag1.797_2_n)),'0-0') AS '797_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.798_3_n),'-',GROUP_CONCAT(sag1.798_2_n)),'0-0') AS '798_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.800_3_n),'-',GROUP_CONCAT(sag1.800_2_n)),'0-0') AS '800_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.801_3_n),'-',GROUP_CONCAT(sag1.801_2_n)),'0-0') AS '801_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.802_3_n),'-',GROUP_CONCAT(sag1.802_2_n)),'0-0') AS '802_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.803_3_n),'-',GROUP_CONCAT(sag1.803_2_n)),'0-0') AS '803_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.804_3_n),'-',GROUP_CONCAT(sag1.804_2_n)),'0-0') AS '804_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.805_3_n),'-',GROUP_CONCAT(sag1.805_2_n)),'0-0') AS '805_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.806_3_n),'-',GROUP_CONCAT(sag1.806_2_n)),'0-0') AS '806_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.807_3_n),'-',GROUP_CONCAT(sag1.807_2_n)),'0-0') AS '807_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.808_3_n),'-',GROUP_CONCAT(sag1.808_2_n)),'0-0') AS '808_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.809_3_n),'-',GROUP_CONCAT(sag1.809_2_n)),'0-0') AS '809_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.810_3_n),'-',GROUP_CONCAT(sag1.810_2_n)),'0-0') AS '810_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.811_3_n),'-',GROUP_CONCAT(sag1.811_2_n)),'0-0') AS '811_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.812_3_n),'-',GROUP_CONCAT(sag1.812_2_n)),'0-0') AS '812_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.813_3_n),'-',GROUP_CONCAT(sag1.813_2_n)),'0-0') AS '813_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.1538_3_n),'-',GROUP_CONCAT(sag1.1538_2_n)),'0-0') AS '1538_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.814_3_n),'-',GROUP_CONCAT(sag1.814_2_n)),'0-0') AS '814_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.815_3_n),'-',GROUP_CONCAT(sag1.815_2_n)),'0-0') AS '815_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.816_3_n),'-',GROUP_CONCAT(sag1.816_2_n)),'0-0') AS '816_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.817_3_n),'-',GROUP_CONCAT(sag1.817_2_n)),'0-0') AS '817_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.818_3_n),'-',GROUP_CONCAT(sag1.818_2_n)),'0-0') AS '818_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.819_3_n),'-',GROUP_CONCAT(sag1.819_2_n)),'0-0') AS '819_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.820_3_n),'-',GROUP_CONCAT(sag1.820_2_n)),'0-0') AS '820_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.821_3_n),'-',GROUP_CONCAT(sag1.821_2_n)),'0-0') AS '821_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.822_3_n),'-',GROUP_CONCAT(sag1.822_2_n)),'0-0') AS '822_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.823_3_n),'-',GROUP_CONCAT(sag1.823_2_n)),'0-0') AS '823_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.828_3_n),'-',GROUP_CONCAT(sag1.828_2_n)),'0-0') AS '828_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.829_3_n),'-',GROUP_CONCAT(sag1.829_2_n)),'0-0') AS '829_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.831_3_n),'-',GROUP_CONCAT(sag1.831_2_n)),'0-0') AS '831_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.830_3_n),'-',GROUP_CONCAT(sag1.830_2_n)),'0-0') AS '830_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.833_3_n),'-',GROUP_CONCAT(sag1.833_2_n)),'0-0') AS '833_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.832_3_n),'-',GROUP_CONCAT(sag1.832_2_n)),'0-0') AS '832_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.827_3_n),'-',GROUP_CONCAT(sag1.827_2_n)),'0-0') AS '827_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.1545_3_n),'-',GROUP_CONCAT(sag1.1545_2_n)),'0-0') AS '1545_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.826_3_n),'-',GROUP_CONCAT(sag1.826_2_n)),'0-0') AS '826_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.1543_3_n),'-',GROUP_CONCAT(sag1.1543_2_n)),'0-0') AS '1543_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.825_3_n),'-',GROUP_CONCAT(sag1.825_2_n)),'0-0') AS '825_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.834_3_n),'-',GROUP_CONCAT(sag1.834_2_n)),'0-0') AS '834_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.835_3_n),'-',GROUP_CONCAT(sag1.835_2_n)),'0-0') AS '835_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.836_3_n),'-',GROUP_CONCAT(sag1.836_2_n)),'0-0') AS '836_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.837_3_n),'-',GROUP_CONCAT(sag1.837_2_n)),'0-0') AS '837_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.838_3_n),'-',GROUP_CONCAT(sag1.838_2_n)),'0-0') AS '838_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.1540_3_n),'-',GROUP_CONCAT(sag1.1540_2_n)),'0-0') AS '1540_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.840_3_n),'-',GROUP_CONCAT(sag1.840_2_n)),'0-0') AS '840_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.841_3_n),'-',GROUP_CONCAT(sag1.841_2_n)),'0-0') AS '841_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.842_3_n),'-',GROUP_CONCAT(sag1.842_2_n)),'0-0') AS '842_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.843_3_n),'-',GROUP_CONCAT(sag1.843_2_n)),'0-0') AS '843_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.1542_3_n),'-',GROUP_CONCAT(sag1.1542_2_n)),'0-0') AS '1542_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.844_3_n),'-',GROUP_CONCAT(sag1.844_2_n)),'0-0') AS '844_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.846_3_n),'-',GROUP_CONCAT(sag1.846_2_n)),'0-0') AS '846_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.848_3_n),'-',GROUP_CONCAT(sag1.848_2_n)),'0-0') AS '848_3_2_n',
IFNULL(CONCAT(GROUP_CONCAT(sag1.847_3_n),'-',GROUP_CONCAT(sag1.847_2_n)),'0-0') AS '847_3_2_n'

 
FROM
(
SELECT sag.name,
CASE WHEN sag.dataelementid=767 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '767_2_k',
CASE WHEN sag.dataelementid=767 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '767_3_k',
CASE WHEN sag.dataelementid=768 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '768_2_k',
CASE WHEN sag.dataelementid=768 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '768_3_k',
CASE WHEN sag.dataelementid=769 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '769_2_k',
CASE WHEN sag.dataelementid=769 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '769_3_k',
CASE WHEN sag.dataelementid=770 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '770_2_k',
CASE WHEN sag.dataelementid=770 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '770_3_k',
CASE WHEN sag.dataelementid=771 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '771_2_k',
CASE WHEN sag.dataelementid=771 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '771_3_k',
CASE WHEN sag.dataelementid=772 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '772_2_k',
CASE WHEN sag.dataelementid=772 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '772_3_k',
CASE WHEN sag.dataelementid=773 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '773_2_k',
CASE WHEN sag.dataelementid=773 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '773_3_k',
CASE WHEN sag.dataelementid=774 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '774_2_k',
CASE WHEN sag.dataelementid=774 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '774_3_k',
CASE WHEN sag.dataelementid=775 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '775_2_k',
CASE WHEN sag.dataelementid=775 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '775_3_k',
CASE WHEN sag.dataelementid=776 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '776_2_k',
CASE WHEN sag.dataelementid=776 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '776_3_k',
CASE WHEN sag.dataelementid=777 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '777_2_k',
CASE WHEN sag.dataelementid=777 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '777_3_k',
CASE WHEN sag.dataelementid=778 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '778_2_k',
CASE WHEN sag.dataelementid=778 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '778_3_k',
CASE WHEN sag.dataelementid=779 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '779_2_k',
CASE WHEN sag.dataelementid=779 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '779_3_k',
CASE WHEN sag.dataelementid=780 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '780_2_k',
CASE WHEN sag.dataelementid=780 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '780_3_k',
CASE WHEN sag.dataelementid=781 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '781_2_k',
CASE WHEN sag.dataelementid=781 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '781_3_k',
CASE WHEN sag.dataelementid=782 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '782_2_k',
CASE WHEN sag.dataelementid=782 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '782_3_k',
CASE WHEN sag.dataelementid=783 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '783_2_k',
CASE WHEN sag.dataelementid=783 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '783_3_k',
CASE WHEN sag.dataelementid=784 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '784_2_k',
CASE WHEN sag.dataelementid=784 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '784_3_k',
CASE WHEN sag.dataelementid=785 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '785_2_k',
CASE WHEN sag.dataelementid=785 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '785_3_k',
CASE WHEN sag.dataelementid=786 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '786_2_k',
CASE WHEN sag.dataelementid=786 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '786_3_k',
CASE WHEN sag.dataelementid=787 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '787_2_k',
CASE WHEN sag.dataelementid=787 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '787_3_k',
CASE WHEN sag.dataelementid=789 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '789_2_k',
CASE WHEN sag.dataelementid=789 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '789_3_k',
CASE WHEN sag.dataelementid=1534 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '1534_2_k',
CASE WHEN sag.dataelementid=1534 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '1534_3_k',
CASE WHEN sag.dataelementid=790 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '790_2_k',
CASE WHEN sag.dataelementid=790 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '790_3_k',
CASE WHEN sag.dataelementid=791 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '791_2_k',
CASE WHEN sag.dataelementid=791 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '791_3_k',
CASE WHEN sag.dataelementid=1536 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '1536_2_k',
CASE WHEN sag.dataelementid=1536 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '1536_3_k',
CASE WHEN sag.dataelementid=792 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '792_2_k',
CASE WHEN sag.dataelementid=792 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '792_3_k',
CASE WHEN sag.dataelementid=793 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '793_2_k',
CASE WHEN sag.dataelementid=793 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '793_3_k',
CASE WHEN sag.dataelementid=794 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '794_2_k',
CASE WHEN sag.dataelementid=794 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '794_3_k',
CASE WHEN sag.dataelementid=795 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '795_2_k',
CASE WHEN sag.dataelementid=795 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '795_3_k',
CASE WHEN sag.dataelementid=796 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '796_2_k',
CASE WHEN sag.dataelementid=796 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '796_3_k',
CASE WHEN sag.dataelementid=797 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '797_2_k',
CASE WHEN sag.dataelementid=797 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '797_3_k',
CASE WHEN sag.dataelementid=798 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '798_2_k',
CASE WHEN sag.dataelementid=798 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '798_3_k',
CASE WHEN sag.dataelementid=800 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '800_2_k',
CASE WHEN sag.dataelementid=800 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '800_3_k',
CASE WHEN sag.dataelementid=801 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '801_2_k',
CASE WHEN sag.dataelementid=801 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '801_3_k',
CASE WHEN sag.dataelementid=802 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '802_2_k',
CASE WHEN sag.dataelementid=802 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '802_3_k',
CASE WHEN sag.dataelementid=803 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '803_2_k',
CASE WHEN sag.dataelementid=803 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '803_3_k',
CASE WHEN sag.dataelementid=804 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '804_2_k',
CASE WHEN sag.dataelementid=804 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '804_3_k',
CASE WHEN sag.dataelementid=805 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '805_2_k',
CASE WHEN sag.dataelementid=805 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '805_3_k',
CASE WHEN sag.dataelementid=806 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '806_2_k',
CASE WHEN sag.dataelementid=806 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '806_3_k',
CASE WHEN sag.dataelementid=807 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '807_2_k',
CASE WHEN sag.dataelementid=807 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '807_3_k',
CASE WHEN sag.dataelementid=808 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '808_2_k',
CASE WHEN sag.dataelementid=808 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '808_3_k',
CASE WHEN sag.dataelementid=809 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '809_2_k',
CASE WHEN sag.dataelementid=809 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '809_3_k',
CASE WHEN sag.dataelementid=810 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '810_2_k',
CASE WHEN sag.dataelementid=810 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '810_3_k',
CASE WHEN sag.dataelementid=811 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '811_2_k',
CASE WHEN sag.dataelementid=811 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '811_3_k',
CASE WHEN sag.dataelementid=812 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '812_2_k',
CASE WHEN sag.dataelementid=812 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '812_3_k',
CASE WHEN sag.dataelementid=813 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '813_2_k',
CASE WHEN sag.dataelementid=813 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '813_3_k',
CASE WHEN sag.dataelementid=1538 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '1538_2_k',
CASE WHEN sag.dataelementid=1538 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '1538_3_k',
CASE WHEN sag.dataelementid=814 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '814_2_k',
CASE WHEN sag.dataelementid=814 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '814_3_k',
CASE WHEN sag.dataelementid=815 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '815_2_k',
CASE WHEN sag.dataelementid=815 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '815_3_k',
CASE WHEN sag.dataelementid=816 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '816_2_k',
CASE WHEN sag.dataelementid=816 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '816_3_k',
CASE WHEN sag.dataelementid=817 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '817_2_k',
CASE WHEN sag.dataelementid=817 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '817_3_k',
CASE WHEN sag.dataelementid=818 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '818_2_k',
CASE WHEN sag.dataelementid=818 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '818_3_k',
CASE WHEN sag.dataelementid=819 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '819_2_k',
CASE WHEN sag.dataelementid=819 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '819_3_k',
CASE WHEN sag.dataelementid=820 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '820_2_k',
CASE WHEN sag.dataelementid=820 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '820_3_k',
CASE WHEN sag.dataelementid=821 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '821_2_k',
CASE WHEN sag.dataelementid=821 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '821_3_k',
CASE WHEN sag.dataelementid=822 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '822_2_k',
CASE WHEN sag.dataelementid=822 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '822_3_k',
CASE WHEN sag.dataelementid=823 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '823_2_k',
CASE WHEN sag.dataelementid=823 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '823_3_k',
CASE WHEN sag.dataelementid=828 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '828_2_k',
CASE WHEN sag.dataelementid=828 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '828_3_k',
CASE WHEN sag.dataelementid=829 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '829_2_k',
CASE WHEN sag.dataelementid=829 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '829_3_k',
CASE WHEN sag.dataelementid=831 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '831_2_k',
CASE WHEN sag.dataelementid=831 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '831_3_k',
CASE WHEN sag.dataelementid=830 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '830_2_k',
CASE WHEN sag.dataelementid=830 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '830_3_k',
CASE WHEN sag.dataelementid=833 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '833_2_k',
CASE WHEN sag.dataelementid=833 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '833_3_k',
CASE WHEN sag.dataelementid=832 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '832_2_k',
CASE WHEN sag.dataelementid=832 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '832_3_k',
CASE WHEN sag.dataelementid=827 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '827_2_k',
CASE WHEN sag.dataelementid=827 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '827_3_k',
CASE WHEN sag.dataelementid=1545 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '1545_2_k',
CASE WHEN sag.dataelementid=1545 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '1545_3_k',
CASE WHEN sag.dataelementid=826 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '826_2_k',
CASE WHEN sag.dataelementid=826 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '826_3_k',
CASE WHEN sag.dataelementid=1543 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '1543_2_k',
CASE WHEN sag.dataelementid=1543 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '1543_3_k',
CASE WHEN sag.dataelementid=825 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '825_2_k',
CASE WHEN sag.dataelementid=825 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '825_3_k',
CASE WHEN sag.dataelementid=834 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '834_2_k',
CASE WHEN sag.dataelementid=834 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '834_3_k',
CASE WHEN sag.dataelementid=835 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '835_2_k',
CASE WHEN sag.dataelementid=835 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '835_3_k',
CASE WHEN sag.dataelementid=836 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '836_2_k',
CASE WHEN sag.dataelementid=836 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '836_3_k',
CASE WHEN sag.dataelementid=837 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '837_2_k',
CASE WHEN sag.dataelementid=837 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '837_3_k',
CASE WHEN sag.dataelementid=838 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '838_2_k',
CASE WHEN sag.dataelementid=838 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '838_3_k',
CASE WHEN sag.dataelementid=1540 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '1540_2_k',
CASE WHEN sag.dataelementid=1540 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '1540_3_k',
CASE WHEN sag.dataelementid=840 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '840_2_k',
CASE WHEN sag.dataelementid=840 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '840_3_k',
CASE WHEN sag.dataelementid=841 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '841_2_k',
CASE WHEN sag.dataelementid=841 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '841_3_k',
CASE WHEN sag.dataelementid=842 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '842_2_k',
CASE WHEN sag.dataelementid=842 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '842_3_k',
CASE WHEN sag.dataelementid=843 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '843_2_k',
CASE WHEN sag.dataelementid=843 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '843_3_k',
CASE WHEN sag.dataelementid=1542 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '1542_2_k',
CASE WHEN sag.dataelementid=1542 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '1542_3_k',
CASE WHEN sag.dataelementid=844 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '844_2_k',
CASE WHEN sag.dataelementid=844 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '844_3_k',
CASE WHEN sag.dataelementid=846 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '846_2_k',
CASE WHEN sag.dataelementid=846 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '846_3_k',
CASE WHEN sag.dataelementid=848 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '848_2_k',
CASE WHEN sag.dataelementid=848 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '848_3_k',
CASE WHEN sag.dataelementid=847 AND sag.categoryoptioncomboid=2 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '847_2_k',
CASE WHEN sag.dataelementid=847 AND sag.categoryoptioncomboid=3 AND sag.name='Karwan Bazar Market' THEN sag.value END AS '847_3_k',
CASE WHEN sag.dataelementid=767 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '767_2_m',
CASE WHEN sag.dataelementid=767 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '767_3_m',
CASE WHEN sag.dataelementid=768 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '768_2_m',
CASE WHEN sag.dataelementid=768 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '768_3_m',
CASE WHEN sag.dataelementid=769 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '769_2_m',
CASE WHEN sag.dataelementid=769 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '769_3_m',
CASE WHEN sag.dataelementid=770 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '770_2_m',
CASE WHEN sag.dataelementid=770 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '770_3_m',
CASE WHEN sag.dataelementid=771 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '771_2_m',
CASE WHEN sag.dataelementid=771 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '771_3_m',
CASE WHEN sag.dataelementid=772 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '772_2_m',
CASE WHEN sag.dataelementid=772 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '772_3_m',
CASE WHEN sag.dataelementid=773 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '773_2_m',
CASE WHEN sag.dataelementid=773 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '773_3_m',
CASE WHEN sag.dataelementid=774 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '774_2_m',
CASE WHEN sag.dataelementid=774 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '774_3_m',
CASE WHEN sag.dataelementid=775 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '775_2_m',
CASE WHEN sag.dataelementid=775 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '775_3_m',
CASE WHEN sag.dataelementid=776 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '776_2_m',
CASE WHEN sag.dataelementid=776 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '776_3_m',
CASE WHEN sag.dataelementid=777 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '777_2_m',
CASE WHEN sag.dataelementid=777 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '777_3_m',
CASE WHEN sag.dataelementid=778 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '778_2_m',
CASE WHEN sag.dataelementid=778 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '778_3_m',
CASE WHEN sag.dataelementid=779 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '779_2_m',
CASE WHEN sag.dataelementid=779 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '779_3_m',
CASE WHEN sag.dataelementid=780 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '780_2_m',
CASE WHEN sag.dataelementid=780 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '780_3_m',
CASE WHEN sag.dataelementid=781 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '781_2_m',
CASE WHEN sag.dataelementid=781 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '781_3_m',
CASE WHEN sag.dataelementid=782 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '782_2_m',
CASE WHEN sag.dataelementid=782 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '782_3_m',
CASE WHEN sag.dataelementid=783 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '783_2_m',
CASE WHEN sag.dataelementid=783 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '783_3_m',
CASE WHEN sag.dataelementid=784 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '784_2_m',
CASE WHEN sag.dataelementid=784 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '784_3_m',
CASE WHEN sag.dataelementid=785 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '785_2_m',
CASE WHEN sag.dataelementid=785 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '785_3_m',
CASE WHEN sag.dataelementid=786 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '786_2_m',
CASE WHEN sag.dataelementid=786 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '786_3_m',
CASE WHEN sag.dataelementid=787 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '787_2_m',
CASE WHEN sag.dataelementid=787 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '787_3_m',
CASE WHEN sag.dataelementid=789 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '789_2_m',
CASE WHEN sag.dataelementid=789 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '789_3_m',
CASE WHEN sag.dataelementid=1534 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '1534_2_m',
CASE WHEN sag.dataelementid=1534 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '1534_3_m',
CASE WHEN sag.dataelementid=790 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '790_2_m',
CASE WHEN sag.dataelementid=790 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '790_3_m',
CASE WHEN sag.dataelementid=791 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '791_2_m',
CASE WHEN sag.dataelementid=791 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '791_3_m',
CASE WHEN sag.dataelementid=1536 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '1536_2_m',
CASE WHEN sag.dataelementid=1536 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '1536_3_m',
CASE WHEN sag.dataelementid=792 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '792_2_m',
CASE WHEN sag.dataelementid=792 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '792_3_m',
CASE WHEN sag.dataelementid=793 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '793_2_m',
CASE WHEN sag.dataelementid=793 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '793_3_m',
CASE WHEN sag.dataelementid=794 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '794_2_m',
CASE WHEN sag.dataelementid=794 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '794_3_m',
CASE WHEN sag.dataelementid=795 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '795_2_m',
CASE WHEN sag.dataelementid=795 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '795_3_m',
CASE WHEN sag.dataelementid=796 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '796_2_m',
CASE WHEN sag.dataelementid=796 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '796_3_m',
CASE WHEN sag.dataelementid=797 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '797_2_m',
CASE WHEN sag.dataelementid=797 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '797_3_m',
CASE WHEN sag.dataelementid=798 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '798_2_m',
CASE WHEN sag.dataelementid=798 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '798_3_m',
CASE WHEN sag.dataelementid=800 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '800_2_m',
CASE WHEN sag.dataelementid=800 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '800_3_m',
CASE WHEN sag.dataelementid=801 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '801_2_m',
CASE WHEN sag.dataelementid=801 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '801_3_m',
CASE WHEN sag.dataelementid=802 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '802_2_m',
CASE WHEN sag.dataelementid=802 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '802_3_m',
CASE WHEN sag.dataelementid=803 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '803_2_m',
CASE WHEN sag.dataelementid=803 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '803_3_m',
CASE WHEN sag.dataelementid=804 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '804_2_m',
CASE WHEN sag.dataelementid=804 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '804_3_m',
CASE WHEN sag.dataelementid=805 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '805_2_m',
CASE WHEN sag.dataelementid=805 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '805_3_m',
CASE WHEN sag.dataelementid=806 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '806_2_m',
CASE WHEN sag.dataelementid=806 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '806_3_m',
CASE WHEN sag.dataelementid=807 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '807_2_m',
CASE WHEN sag.dataelementid=807 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '807_3_m',
CASE WHEN sag.dataelementid=808 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '808_2_m',
CASE WHEN sag.dataelementid=808 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '808_3_m',
CASE WHEN sag.dataelementid=809 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '809_2_m',
CASE WHEN sag.dataelementid=809 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '809_3_m',
CASE WHEN sag.dataelementid=810 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '810_2_m',
CASE WHEN sag.dataelementid=810 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '810_3_m',
CASE WHEN sag.dataelementid=811 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '811_2_m',
CASE WHEN sag.dataelementid=811 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '811_3_m',
CASE WHEN sag.dataelementid=812 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '812_2_m',
CASE WHEN sag.dataelementid=812 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '812_3_m',
CASE WHEN sag.dataelementid=813 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '813_2_m',
CASE WHEN sag.dataelementid=813 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '813_3_m',
CASE WHEN sag.dataelementid=1538 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '1538_2_m',
CASE WHEN sag.dataelementid=1538 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '1538_3_m',
CASE WHEN sag.dataelementid=814 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '814_2_m',
CASE WHEN sag.dataelementid=814 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '814_3_m',
CASE WHEN sag.dataelementid=815 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '815_2_m',
CASE WHEN sag.dataelementid=815 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '815_3_m',
CASE WHEN sag.dataelementid=816 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '816_2_m',
CASE WHEN sag.dataelementid=816 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '816_3_m',
CASE WHEN sag.dataelementid=817 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '817_2_m',
CASE WHEN sag.dataelementid=817 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '817_3_m',
CASE WHEN sag.dataelementid=818 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '818_2_m',
CASE WHEN sag.dataelementid=818 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '818_3_m',
CASE WHEN sag.dataelementid=819 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '819_2_m',
CASE WHEN sag.dataelementid=819 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '819_3_m',
CASE WHEN sag.dataelementid=820 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '820_2_m',
CASE WHEN sag.dataelementid=820 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '820_3_m',
CASE WHEN sag.dataelementid=821 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '821_2_m',
CASE WHEN sag.dataelementid=821 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '821_3_m',
CASE WHEN sag.dataelementid=822 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '822_2_m',
CASE WHEN sag.dataelementid=822 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '822_3_m',
CASE WHEN sag.dataelementid=823 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '823_2_m',
CASE WHEN sag.dataelementid=823 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '823_3_m',
CASE WHEN sag.dataelementid=828 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '828_2_m',
CASE WHEN sag.dataelementid=828 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '828_3_m',
CASE WHEN sag.dataelementid=829 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '829_2_m',
CASE WHEN sag.dataelementid=829 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '829_3_m',
CASE WHEN sag.dataelementid=831 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '831_2_m',
CASE WHEN sag.dataelementid=831 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '831_3_m',
CASE WHEN sag.dataelementid=830 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '830_2_m',
CASE WHEN sag.dataelementid=830 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '830_3_m',
CASE WHEN sag.dataelementid=833 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '833_2_m',
CASE WHEN sag.dataelementid=833 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '833_3_m',
CASE WHEN sag.dataelementid=832 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '832_2_m',
CASE WHEN sag.dataelementid=832 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '832_3_m',
CASE WHEN sag.dataelementid=827 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '827_2_m',
CASE WHEN sag.dataelementid=827 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '827_3_m',
CASE WHEN sag.dataelementid=1545 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '1545_2_m',
CASE WHEN sag.dataelementid=1545 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '1545_3_m',
CASE WHEN sag.dataelementid=826 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '826_2_m',
CASE WHEN sag.dataelementid=826 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '826_3_m',
CASE WHEN sag.dataelementid=1543 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '1543_2_m',
CASE WHEN sag.dataelementid=1543 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '1543_3_m',
CASE WHEN sag.dataelementid=825 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '825_2_m',
CASE WHEN sag.dataelementid=825 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '825_3_m',
CASE WHEN sag.dataelementid=834 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '834_2_m',
CASE WHEN sag.dataelementid=834 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '834_3_m',
CASE WHEN sag.dataelementid=835 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '835_2_m',
CASE WHEN sag.dataelementid=835 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '835_3_m',
CASE WHEN sag.dataelementid=836 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '836_2_m',
CASE WHEN sag.dataelementid=836 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '836_3_m',
CASE WHEN sag.dataelementid=837 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '837_2_m',
CASE WHEN sag.dataelementid=837 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '837_3_m',
CASE WHEN sag.dataelementid=838 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '838_2_m',
CASE WHEN sag.dataelementid=838 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '838_3_m',
CASE WHEN sag.dataelementid=1540 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '1540_2_m',
CASE WHEN sag.dataelementid=1540 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '1540_3_m',
CASE WHEN sag.dataelementid=840 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '840_2_m',
CASE WHEN sag.dataelementid=840 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '840_3_m',
CASE WHEN sag.dataelementid=841 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '841_2_m',
CASE WHEN sag.dataelementid=841 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '841_3_m',
CASE WHEN sag.dataelementid=842 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '842_2_m',
CASE WHEN sag.dataelementid=842 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '842_3_m',
CASE WHEN sag.dataelementid=843 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '843_2_m',
CASE WHEN sag.dataelementid=843 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '843_3_m',
CASE WHEN sag.dataelementid=1542 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '1542_2_m',
CASE WHEN sag.dataelementid=1542 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '1542_3_m',
CASE WHEN sag.dataelementid=844 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '844_2_m',
CASE WHEN sag.dataelementid=844 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '844_3_m',
CASE WHEN sag.dataelementid=846 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '846_2_m',
CASE WHEN sag.dataelementid=846 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '846_3_m',
CASE WHEN sag.dataelementid=848 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '848_2_m',
CASE WHEN sag.dataelementid=848 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '848_3_m',
CASE WHEN sag.dataelementid=847 AND sag.categoryoptioncomboid=2 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '847_2_m',
CASE WHEN sag.dataelementid=847 AND sag.categoryoptioncomboid=3 AND sag.name='Mirpur 1 Bazar Market' THEN sag.value END AS '847_3_m',
CASE WHEN sag.dataelementid=767 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '767_2_n',
CASE WHEN sag.dataelementid=767 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '767_3_n',
CASE WHEN sag.dataelementid=768 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '768_2_n',
CASE WHEN sag.dataelementid=768 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '768_3_n',
CASE WHEN sag.dataelementid=769 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '769_2_n',
CASE WHEN sag.dataelementid=769 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '769_3_n',
CASE WHEN sag.dataelementid=770 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '770_2_n',
CASE WHEN sag.dataelementid=770 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '770_3_n',
CASE WHEN sag.dataelementid=771 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '771_2_n',
CASE WHEN sag.dataelementid=771 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '771_3_n',
CASE WHEN sag.dataelementid=772 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '772_2_n',
CASE WHEN sag.dataelementid=772 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '772_3_n',
CASE WHEN sag.dataelementid=773 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '773_2_n',
CASE WHEN sag.dataelementid=773 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '773_3_n',
CASE WHEN sag.dataelementid=774 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '774_2_n',
CASE WHEN sag.dataelementid=774 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '774_3_n',
CASE WHEN sag.dataelementid=775 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '775_2_n',
CASE WHEN sag.dataelementid=775 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '775_3_n',
CASE WHEN sag.dataelementid=776 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '776_2_n',
CASE WHEN sag.dataelementid=776 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '776_3_n',
CASE WHEN sag.dataelementid=777 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '777_2_n',
CASE WHEN sag.dataelementid=777 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '777_3_n',
CASE WHEN sag.dataelementid=778 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '778_2_n',
CASE WHEN sag.dataelementid=778 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '778_3_n',
CASE WHEN sag.dataelementid=779 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '779_2_n',
CASE WHEN sag.dataelementid=779 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '779_3_n',
CASE WHEN sag.dataelementid=780 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '780_2_n',
CASE WHEN sag.dataelementid=780 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '780_3_n',
CASE WHEN sag.dataelementid=781 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '781_2_n',
CASE WHEN sag.dataelementid=781 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '781_3_n',
CASE WHEN sag.dataelementid=782 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '782_2_n',
CASE WHEN sag.dataelementid=782 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '782_3_n',
CASE WHEN sag.dataelementid=783 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '783_2_n',
CASE WHEN sag.dataelementid=783 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '783_3_n',
CASE WHEN sag.dataelementid=784 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '784_2_n',
CASE WHEN sag.dataelementid=784 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '784_3_n',
CASE WHEN sag.dataelementid=785 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '785_2_n',
CASE WHEN sag.dataelementid=785 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '785_3_n',
CASE WHEN sag.dataelementid=786 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '786_2_n',
CASE WHEN sag.dataelementid=786 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '786_3_n',
CASE WHEN sag.dataelementid=787 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '787_2_n',
CASE WHEN sag.dataelementid=787 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '787_3_n',
CASE WHEN sag.dataelementid=789 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '789_2_n',
CASE WHEN sag.dataelementid=789 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '789_3_n',
CASE WHEN sag.dataelementid=1534 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '1534_2_n',
CASE WHEN sag.dataelementid=1534 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '1534_3_n',
CASE WHEN sag.dataelementid=790 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '790_2_n',
CASE WHEN sag.dataelementid=790 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '790_3_n',
CASE WHEN sag.dataelementid=791 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '791_2_n',
CASE WHEN sag.dataelementid=791 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '791_3_n',
CASE WHEN sag.dataelementid=1536 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '1536_2_n',
CASE WHEN sag.dataelementid=1536 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '1536_3_n',
CASE WHEN sag.dataelementid=792 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '792_2_n',
CASE WHEN sag.dataelementid=792 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '792_3_n',
CASE WHEN sag.dataelementid=793 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '793_2_n',
CASE WHEN sag.dataelementid=793 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '793_3_n',
CASE WHEN sag.dataelementid=794 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '794_2_n',
CASE WHEN sag.dataelementid=794 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '794_3_n',
CASE WHEN sag.dataelementid=795 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '795_2_n',
CASE WHEN sag.dataelementid=795 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '795_3_n',
CASE WHEN sag.dataelementid=796 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '796_2_n',
CASE WHEN sag.dataelementid=796 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '796_3_n',
CASE WHEN sag.dataelementid=797 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '797_2_n',
CASE WHEN sag.dataelementid=797 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '797_3_n',
CASE WHEN sag.dataelementid=798 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '798_2_n',
CASE WHEN sag.dataelementid=798 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '798_3_n',
CASE WHEN sag.dataelementid=800 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '800_2_n',
CASE WHEN sag.dataelementid=800 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '800_3_n',
CASE WHEN sag.dataelementid=801 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '801_2_n',
CASE WHEN sag.dataelementid=801 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '801_3_n',
CASE WHEN sag.dataelementid=802 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '802_2_n',
CASE WHEN sag.dataelementid=802 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '802_3_n',
CASE WHEN sag.dataelementid=803 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '803_2_n',
CASE WHEN sag.dataelementid=803 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '803_3_n',
CASE WHEN sag.dataelementid=804 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '804_2_n',
CASE WHEN sag.dataelementid=804 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '804_3_n',
CASE WHEN sag.dataelementid=805 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '805_2_n',
CASE WHEN sag.dataelementid=805 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '805_3_n',
CASE WHEN sag.dataelementid=806 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '806_2_n',
CASE WHEN sag.dataelementid=806 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '806_3_n',
CASE WHEN sag.dataelementid=807 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '807_2_n',
CASE WHEN sag.dataelementid=807 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '807_3_n',
CASE WHEN sag.dataelementid=808 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '808_2_n',
CASE WHEN sag.dataelementid=808 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '808_3_n',
CASE WHEN sag.dataelementid=809 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '809_2_n',
CASE WHEN sag.dataelementid=809 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '809_3_n',
CASE WHEN sag.dataelementid=810 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '810_2_n',
CASE WHEN sag.dataelementid=810 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '810_3_n',
CASE WHEN sag.dataelementid=811 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '811_2_n',
CASE WHEN sag.dataelementid=811 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '811_3_n',
CASE WHEN sag.dataelementid=812 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '812_2_n',
CASE WHEN sag.dataelementid=812 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '812_3_n',
CASE WHEN sag.dataelementid=813 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '813_2_n',
CASE WHEN sag.dataelementid=813 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '813_3_n',
CASE WHEN sag.dataelementid=1538 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '1538_2_n',
CASE WHEN sag.dataelementid=1538 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '1538_3_n',
CASE WHEN sag.dataelementid=814 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '814_2_n',
CASE WHEN sag.dataelementid=814 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '814_3_n',
CASE WHEN sag.dataelementid=815 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '815_2_n',
CASE WHEN sag.dataelementid=815 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '815_3_n',
CASE WHEN sag.dataelementid=816 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '816_2_n',
CASE WHEN sag.dataelementid=816 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '816_3_n',
CASE WHEN sag.dataelementid=817 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '817_2_n',
CASE WHEN sag.dataelementid=817 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '817_3_n',
CASE WHEN sag.dataelementid=818 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '818_2_n',
CASE WHEN sag.dataelementid=818 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '818_3_n',
CASE WHEN sag.dataelementid=819 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '819_2_n',
CASE WHEN sag.dataelementid=819 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '819_3_n',
CASE WHEN sag.dataelementid=820 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '820_2_n',
CASE WHEN sag.dataelementid=820 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '820_3_n',
CASE WHEN sag.dataelementid=821 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '821_2_n',
CASE WHEN sag.dataelementid=821 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '821_3_n',
CASE WHEN sag.dataelementid=822 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '822_2_n',
CASE WHEN sag.dataelementid=822 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '822_3_n',
CASE WHEN sag.dataelementid=823 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '823_2_n',
CASE WHEN sag.dataelementid=823 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '823_3_n',
CASE WHEN sag.dataelementid=828 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '828_2_n',
CASE WHEN sag.dataelementid=828 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '828_3_n',
CASE WHEN sag.dataelementid=829 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '829_2_n',
CASE WHEN sag.dataelementid=829 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '829_3_n',
CASE WHEN sag.dataelementid=831 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '831_2_n',
CASE WHEN sag.dataelementid=831 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '831_3_n',
CASE WHEN sag.dataelementid=830 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '830_2_n',
CASE WHEN sag.dataelementid=830 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '830_3_n',
CASE WHEN sag.dataelementid=833 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '833_2_n',
CASE WHEN sag.dataelementid=833 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '833_3_n',
CASE WHEN sag.dataelementid=832 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '832_2_n',
CASE WHEN sag.dataelementid=832 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '832_3_n',
CASE WHEN sag.dataelementid=827 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '827_2_n',
CASE WHEN sag.dataelementid=827 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '827_3_n',
CASE WHEN sag.dataelementid=1545 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '1545_2_n',
CASE WHEN sag.dataelementid=1545 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '1545_3_n',
CASE WHEN sag.dataelementid=826 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '826_2_n',
CASE WHEN sag.dataelementid=826 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '826_3_n',
CASE WHEN sag.dataelementid=1543 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '1543_2_n',
CASE WHEN sag.dataelementid=1543 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '1543_3_n',
CASE WHEN sag.dataelementid=825 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '825_2_n',
CASE WHEN sag.dataelementid=825 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '825_3_n',
CASE WHEN sag.dataelementid=834 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '834_2_n',
CASE WHEN sag.dataelementid=834 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '834_3_n',
CASE WHEN sag.dataelementid=835 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '835_2_n',
CASE WHEN sag.dataelementid=835 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '835_3_n',
CASE WHEN sag.dataelementid=836 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '836_2_n',
CASE WHEN sag.dataelementid=836 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '836_3_n',
CASE WHEN sag.dataelementid=837 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '837_2_n',
CASE WHEN sag.dataelementid=837 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '837_3_n',
CASE WHEN sag.dataelementid=838 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '838_2_n',
CASE WHEN sag.dataelementid=838 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '838_3_n',
CASE WHEN sag.dataelementid=1540 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '1540_2_n',
CASE WHEN sag.dataelementid=1540 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '1540_3_n',
CASE WHEN sag.dataelementid=840 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '840_2_n',
CASE WHEN sag.dataelementid=840 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '840_3_n',
CASE WHEN sag.dataelementid=841 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '841_2_n',
CASE WHEN sag.dataelementid=841 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '841_3_n',
CASE WHEN sag.dataelementid=842 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '842_2_n',
CASE WHEN sag.dataelementid=842 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '842_3_n',
CASE WHEN sag.dataelementid=843 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '843_2_n',
CASE WHEN sag.dataelementid=843 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '843_3_n',
CASE WHEN sag.dataelementid=1542 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '1542_2_n',
CASE WHEN sag.dataelementid=1542 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '1542_3_n',
CASE WHEN sag.dataelementid=844 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '844_2_n',
CASE WHEN sag.dataelementid=844 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '844_3_n',
CASE WHEN sag.dataelementid=846 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '846_2_n',
CASE WHEN sag.dataelementid=846 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '846_3_n',
CASE WHEN sag.dataelementid=848 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '848_2_n',
CASE WHEN sag.dataelementid=848 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '848_3_n',
CASE WHEN sag.dataelementid=847 AND sag.categoryoptioncomboid=2 AND sag.name='New Market market' THEN sag.value END AS '847_2_n',
CASE WHEN sag.dataelementid=847 AND sag.categoryoptioncomboid=3 AND sag.name='New Market market' THEN sag.value END AS '847_3_n'

FROM
(
SELECT asd.organisationunitid,asd.name,asd1.dataelementid,asd1.categoryoptioncomboid,asd1.value 
FROM
(
SELECT ou.organisationunitid,ou.name
FROM organisationunit ou
WHERE ou.name  IN ('Mirpur 1 Bazar Market','Karwan Bazar Market','New Market Market')
)asd

LEFT JOIN

(
SELECT dv.dataelementid,dv.categoryoptioncomboid,dv.value,dv.sourceid,p.startdate
FROM datavalue dv
INNER JOIN period p ON p.periodid=dv.periodid 
WHERE dv.dataelementid IN (767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785,786,787,789,1534,790,791,
                           1536,792,793,794,795,796,797,798,800,801,802,803,804,805,806,807,808,809,810,811,812,813,1538,814,815,
                           816,817,818,819,820,821,822,823,828,829,831,830,833,832,827,1545,826,1543,825,834,835,836,837,838,1540,
                           840,841,842,843,1542,844,846,848,847)
AND dv.categoryoptioncomboid IN (2,3)
AND p.startdate= '2013-12-28' 
AND periodtypeid = 1

)asd1

ON asd.organisationunitid = asd1.sourceid
)sag
)sag1
#GROUP BY sag1.name